### ISSUE TITLE
News Getter

### ISSUE THREAD

**Issue by Mohpann** [acm-uic/SIG-Algorithmic-Trading#2]
I need some to implement basic functionality for our new getter program. This program will get the top headlines for a specific field like technology, geopolitics, and fed policy. This program's output will be piped to the sentiment analysis program. It should have some string outputs in either an array or dict.

I have provided comments in the file "newsGetter.py" in the SentimentAnalysis folder to help. If you want to work on this, assign yourself to this issue and hack away. Thanks.

**Comment by Rahul20037237** [comment]
take

**Comment by Mohpann** [comment]
I used an RSS feed reader to get news headlines. Further functionality is needed to get headlines from a large list of RSS feeds.
